#! /bin/sh

# Variable Defines
color0=#3B4252
color4=#D8DEE9

# Make sure sxhkd is always running
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 5
done &

#Clean lingering programs when reloaded
"$HOME/.config/bspwm/clean" &

#Fix Mouse curoor on startup
xsetroot -cursor_name left_ptr

#Monitor Config
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#BSPWM Config
bspc config border_width        0
bspc config top_padding         25
bspc config right_padding       0
bspc config left_padding        0
bspc config bottom_padding      0
bspc config window_gap          0
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

bspc config focused_border_color "$color0"
bspc config normal_border_color  "$color0"
bspc config active_border_color  "$color0"
bspc config presel_feedback_color "$color4"
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"

#Application Rules
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Gimp-2.10 desktop='^8' follow=on
bspc rule -a wine desktop='^7' state=floating follow=on
bspc rule -a variety state=floating
bspc rule -a Firefox-esr desktop='^1'
bspc rule -a mpv state=floating
bspc rule -a Code dekstop='^4'
bspc rule -a Sublime_text desktop='^4'
bspc rule -a libreoffice desktop='^3'
bspc rule -a feh state=floating
bspc rule -a Pavucontrol state=floating desktop='^10' follow=on
bspc rule -a zoom state=floating desktop='^7'
bspc rule -a Tk state=floating
bspc rule -a gnuplot_qt state=floating
bspc rule -a Yad state=floating
bspc rule -a Simplescreenrecorder state=floating
bspc rule -a LearnOpenGL state=floating
#bspc rule -a Wine state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Discord desktop='^6'
#bspc rule -a synergy desktop='^9'

#Auto-Start
sleep 0.50
# urxvtc &   # i don't use urxvt
bash ~/.config/polybar/launch.sh &
lxpolkit &
picom --config "$HOME/.config/picom.conf" &
#variety &
flameshot &
sleep 0.5
#pingresult=$(ping -c 1 1.1.1.1 > /dev/null ; echo $?)
#while [ $pingresult -ne 0 ]; do
#  pingresult=$(ping -c 1 1.1.1.1 > /dev/null ; echo $?)
#done

# Extra Files for mrizaln
brightnessctl -r &
brightnessctl -s &
sct 5000 &
feh --bg-fill ~/.config/bspwm/current_wallpaper &
bspc desktop -f ^5
# START_COMMAND=neofetch kitty bash &     # execute $START_COMMAND before bash promt (see ~/.bashrc)        # broken
kitty bash &
kitty htop &
kdeconnect-indicator &
